#!/usr/bin/env sh
# Copyright (C) 2014 Julien Bonjean <julien@bonjean.info>

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

TYPE="${BLOCK_INSTANCE:-mem}"
# PERCENT="${PERCENT:-true}"
PERCENT="false"

awk -v type=$TYPE -v percent=$PERCENT '
/^MemTotal:/ {
	mem_total=$2
}
/^MemFree:/ {
	mem_free=$2
}
/^MemAvailable:/ {
	mem_available=$2
}
/^Buffers:/ {
	buffers=$2
}
/^Cached:/ {
	cached=$2
}
/^SReclaimable:/ {
	sreclaimable=$2
}
/^Shmem:/ {
	shmem=$2
}
/^SwapTotal:/ {
	swap_total=$2
}
/^SwapFree:/ {
	swap_free=$2
}
END {
	if (type == "swap") {
		free=swap_free/1024/1024
		used=(swap_total-swap_free)/1024/1024
		total=swap_total/1024/1024
	} else {
		# MemAvailable is the kernel estimate of memory that can be used
		# without swapping. Fall back for kernels that do not expose it.
		available=mem_available
		if (available == 0) {
			available=mem_free+buffers+cached+sreclaimable-shmem
		}
		free=available/1024/1024
		used=(mem_total-available)/1024/1024
		total=mem_total/1024/1024
	}

	pct=0
	if (total > 0) {
		pct=used/total*100
	}

	# full text
	if (percent == "true" ) {
		printf("   %.1fG/%.1fG (%.f%%)\n", used, total, pct)
	} else {
		printf("   %.1fG/%.1fG\n", used, total)
	}
	# short text
	printf("%.f%%\n", pct)

	# color
	if (pct > 90) {
		print("#FF0000")
	} else if (pct > 80) {
		print("#FFAE00")
	} else if (pct > 70) {
		print("#FFF600")
	}
}
' /proc/meminfo
