#!/usr/bin/env bash
# Copyright (C) 2014 Julien Bonjean <julien@bonjean.info>
# Copyright (C) 2014 Alexander Keller <github@nycroth.com>

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

# original source: https://github.com/vivien/i3blocks-contrib/tree/master/volume
# check the readme: https://github.com/vivien/i3blocks-contrib/blob/master/volume/README.md
#------------------------------------------------------------------------

set -euo pipefail

STEP="${1:-5%}"
MIXER="${2:-default}"

# Detect mixer type
if command -v pactl >/dev/null 2>&1; then
    if amixer -D pulse info >/dev/null 2>&1; then
        MIXER="pulse"
    fi
elif lsmod | grep -q "^jack"; then
    MIXER="jackplug"
fi

# Select first simple control if not specified
SCONTROL="${BLOCK_INSTANCE:-$(amixer -D "$MIXER" scontrols \
  | sed -n "s/Simple mixer control '\([^']*\)',0/\1/p" | head -n1)}"

AMIXER_PARAMS=""
[[ "${NATURAL_MAPPING:-0}" != "0" ]] && AMIXER_PARAMS="-M"

# Handle scroll and click
case "${BLOCK_BUTTON:-0}" in
  3) amixer $AMIXER_PARAMS -q -D "$MIXER" sset "$SCONTROL" toggle ;;
  4) amixer $AMIXER_PARAMS -q -D "$MIXER" sset "$SCONTROL" "${STEP}+" unmute ;;
  5) amixer $AMIXER_PARAMS -q -D "$MIXER" sset "$SCONTROL" "${STEP}-" unmute ;;
esac

# Format output safely (avoid raw ALSA numbers)
read -r volume status < <(
  amixer $AMIXER_PARAMS -D "$MIXER" get "$SCONTROL" |
  awk '
    /\[(on|off)\]/ {
      match($0, /\[([0-9]+%)\].*\[(on|off)\]/, m);
      if (m[1] && m[2]) { print m[1], m[2]; exit }
    }
  '
)

if [[ $status == "off" ]]; then
  echo "MUTE"
else
  echo "$volume"
fi
